on:
  push:
    branches:
      - main
    tags:
      - "*"
  pull_request:

name: CI
jobs:
  build:
    name: Build
    strategy:
      matrix:
        os: [ubuntu-latest, windows-latest]
    runs-on: ${{ matrix.os }}
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@stable

      - name: cargo build (view)
        run: cargo build --release --bin view

      - name: cargo test build
        run: cargo build --tests

      - name: cargo test
        run: cargo test

  shaders:
    name: Build (Rust-GPU shaders)
    runs-on: ubuntu-latest
    steps:
      - uses: actions/checkout@v4
      - uses: dtolnay/rust-toolchain@nightly-2023-07-08
        with:
          components: rust-src, rustc-dev, llvm-tools-preview

      - name: Build shaders
        run: cargo run --release
        working-directory: crates/bin/rust-shader-builder
